version: '3.8'

services:
  db:
    image: postgres:14
    container_name: twodo_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twodo_db
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: twodo_app_container
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/twodo_db
    depends_on:
      - db