{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    # מאפשר ל-ALB לנהל כמה דומיינים על אותו Load Balancer פיזי
    alb.ingress.kubernetes.io/group.name: "twodo-app-stack"
    # קריטי לניתוב לשירותים ב-Namespaces אחרים
    alb.ingress.kubernetes.io/target-type: ip
    # אופציונלי: עוזר לשמור על חיבור יציב בארגו וגרפאנה
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- /* ניתוב לגרפאנה (נמצא ב-Namespace: monitoring) */ -}}
          {{- if contains "grafana" .host }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-stack-grafana
                port:
                  number: 80
          {{- /* ניתוב לארגו (נמצא ב-Namespace: argocd) */ -}}
          {{- else if contains "argocd" .host }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
          {{- /* ניתוב רגיל לאפליקציה (Frontend/Backend) */ -}}
          {{- else }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.backend.name }}-service
                port:
                  number: 5001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.frontend.name }}-service
                port:
                  number: 80
          {{- end }}
    {{- end }}
{{- end }}