apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
spec:
  # שים לב - כאן ב-values השתמשנו פשוט ב-ClusterIP
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      # כאן התיקון: אנחנו מפנים לפורט 5000 ישירות כי זה מה שה-container מאזין לו
      targetPort: 5000
      protocol: TCP
  selector:
    app: {{ .Values.frontend.name }}